### ISSUE TITLE
missing return colon

### ISSUE THREAD

**Issue by jmoral** [simplesamlphp/simplesamlphp-module-expirycheck#8]
Not sure how to tell this. 

Maybe a missing return colon?
https://github.com/simplesamlphp/simplesamlphp-module-expirycheck/blob/25f7df4f514ebae91081e3fd99943f7ea3c009e3/src/Controller/ExpiryCheck.php#L78

@tvdijen

**Comment by tvdijen** [comment]
🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️

... closed in 63d2200
